name: Generate Snake

on:
  schedule:
    # 00:00 and 12:00 UTC every day
    - cron: "0 0,12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#58A6FF&color_dots=#ebedf0,#c6e48b,#7bc96f,#239a3b,#196127
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#58A6FF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
